// <auto-generated />
namespace GameFinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class thirdtrial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirdtrial));
        
        string IMigrationMetadata.Id
        {
            get { return "202011172027206_thirdtrial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
